app/main/urls.py
from flask import Blueprint, g

from . import views, admin_views, errors
from OctBlog.config import OctBlogSettings

main = Blueprint('main', __name__)

main.add_url_rule('/', 'index', views.list_posts)
main.add_url_rule('/posts/', 'posts', views.list_posts)
main.add_url_rule('/wechats/', 'wechats', views.list_wechats)
main.add_url_rule('/posts/<slug>/', 'post_detail', views.post_detail, methods=['GET', 'POST'])
main.add_url_rule('/post/<slug>/', 'post_detail_fix', views.post_detail, defaults={'fix':True})
main.add_url_rule('/posts/<slug>/preview/', 'post_preview', views.post_detail, defaults={'is_preview':True})
main.add_url_rule('/posts/<slug>/<post_type>/preview/', 'post_general_preview', views.post_detail_general)
main.add_url_rule('/pages/<slug>/', 'page_detail', views.post_detail, defaults={'post_type':'page'}, methods=['GET', 'POST'])
main.add_url_rule('/wechats/<slug>/', 'wechat_detail', views.post_detail, defaults={'post_type':'wechat'})
main.add_url_rule('/archive/', 'archive', views.archive)
main.add_url_rule('/users/<username>/', 'author_detail', views.author_detail)
main.add_url_rule('/atom/', 'recent_feed', views.recent_feed)
main.add_url_rule('/sitemap.xml/', 'sitemap', views.sitemap)
main.errorhandler(404)(errors.page_not_found)
main.errorhandler(401)(errors.handle_unauthorized)
main.add_url_rule('/<path:invalid_path>', 'handle_unmatchable', errors.handle_unmatchable)


blog_admin = Blueprint('blog_admin', __name__)

blog_admin.add_url_rule('/', view_func=admin_views.AdminIndex.as_view('index'))

blog_admin.add_url_rule('/posts/', view_func=admin_views.PostsList.as_view('posts'))
blog_admin.add_url_rule('/posts/draft/', view_func=admin_views.DraftList.as_view('drafts'))
blog_admin.add_url_rule('/new-post/', view_func=admin_views.Post.as_view('new_post'))
blog_admin.add_url_rule('/posts/<slug>/', view_func=admin_views.Post.as_view('edit_post'))

blog_admin.add_url_rule('/pages/', view_func=admin_views.PostsList.as_view('pages'), defaults={'post_type':'page'})
blog_admin.add_url_rule('/pages/draft/', view_func=admin_views.DraftList.as_view('page_drafts'), defaults={'post_type':'page'})
blog_admin.add_url_rule('/new-page/', view_func=admin_views.Post.as_view('new_page'), defaults={'post_type':'page'})

blog_admin.add_url_rule('/wechats/', view_func=admin_views.PostsList.as_view('wechats'), defaults={'post_type':'wechat'})
blog_admin.add_url_rule('/wechats/draft/', view_func=admin_views.DraftList.as_view('wechat_drafts'), defaults={'post_type':'wechat'})
blog_admin.add_url_rule('/new-wechat/', view_func=admin_views.Post.as_view('new_wechat'), defaults={'post_type':'wechat'})

blog_admin.add_url_rule('/posts/statistics/', view_func=admin_views.PostStatisticList.as_view('post_statistics'))
blog_admin.add_url_rule('/posts/statistics/<slug>/', view_func=admin_views.PostStatisticDetail.as_view('post_statistics_detail'))

blog_admin.add_url_rule('/posts/comments/', view_func=admin_views.Comment.as_view('comments'))
blog_admin.add_url_rule('/posts/comments/approved/', view_func=admin_views.Comment.as_view('comments_approved'), defaults={'status':'approved'})
blog_admin.add_url_rule('/posts/comments/spam/', view_func=admin_views.Comment.as_view('comments_spam'), defaults={'status':'spam'})
blog_admin.add_url_rule('/posts/comments/<pk>/action/', view_func=admin_views.Comment.as_view('comment_action'))
blog_admin.add_url_rule('/posts/comments/import/', view_func=admin_views.ImportCommentView.as_view('import_comments'))
blog_admin.add_url_rule('/posts/comments/action/', view_func=admin_views.Comments.as_view('comments_action'))

blog_admin.add_url_rule('/su/posts/', view_func=admin_views.SuPostsList.as_view('su_posts'))
blog_admin.add_url_rule('/su/posts/<slug>/', view_func=admin_views.SuPost.as_view('su_post_edit'))
blog_admin.add_url_rule('/su/widgets/', view_func=admin_views.WidgetList.as_view('su_widgets'))
blog_admin.add_url_rule('/su/widgets/create/', view_func=admin_views.Widget.as_view('su_widget'))
blog_admin.add_url_rule('/su/widgets/<pk>/', view_func=admin_views.Widget.as_view('su_widget_edit'))
blog_admin.add_url_rule('/su/export/', view_func=admin_views.SuExportView.as_view('su_export'))

blog_admin.errorhandler(404)(errors.admin_page_not_found)
blog_admin.errorhandler(401)(errors.handle_unauthorized)
blog_admin.errorhandler(403)(errors.handle_forbidden)

ALLOW_WECHAT_PORT = OctBlogSettings['allow_wechat_port']

@blog_admin.before_app_request
def before_request():
    g.allow_wechat_port = ALLOW_WECHAT_PORT


app/main/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# from flask.ext.mongoengine.wtf import model_form
from flask_mongoengine.wtf import model_form
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, TextAreaField, HiddenField, RadioField, FileField, IntegerField
from wtforms import widgets, ValidationError
from wtforms.validators import Required, Length, Email, Regexp, EqualTo, URL, Optional

from . import models

class PostForm(FlaskForm):
    title = StringField('Title', validators=[Required()])
    slug = StringField('Slug', validators=[Required()])
    weight = IntegerField('Weight', default=10)
    raw = TextAreaField('Content')
    abstract = TextAreaField('Abstract')
    category = StringField('Category')
    tags_str = StringField('Tags')
    post_id = HiddenField('post_id')
    post_type = HiddenField('post_type')
    from_draft = HiddenField('from_draft')

    def validate_slug(self, field):
        if self.from_draft.data and self.from_draft.data == 'true':
            posts = models.Draft.objects.filter(slug=field.data)
        else:
            posts = models.Post.objects.filter(slug=field.data)
        if posts.count() > 0:
            if not self.post_id.data or str(posts[0].id) != self.post_id.data:
                raise ValidationError('slug already in use')

SuPostForm = model_form(models.Post, exclude=['pub_time', 'update_time', 'content_html', 'category', 'tags', 'post_type'])

class WidgetForm(FlaskForm):
    title = StringField('Title', validators=[Required()])
    content = TextAreaField('Content', validators=[Required()])
    content_type = RadioField('Content Type', choices=[('markdown', 'markdown'), ('html', 'html')], default='html')
    priority = IntegerField(default=1000000)

class CommentForm(FlaskForm):
    email = StringField('* Email', validators=[Required(), Length(1,128), Email()])
    author = StringField('* Name', validators=[Required(), Length(1,128)])
    homepage = StringField('Homepage', validators=[URL(), Optional()])
    content = TextAreaField('* Comment <small><span class="label label-info">markdown</span></small>', validators=[Required()])
    comment_id = HiddenField('comment_id')

class SessionCommentForm(FlaskForm):
    email = HiddenField('* Email')
    author = HiddenField('* Name')
    homepage = HiddenField('Homepage')
    content = TextAreaField('* Comment', validators=[Required()])
    comment_id = HiddenField('comment_id')

class ImportCommentForm(FlaskForm):
    content = TextAreaField('Content')
    json_file = FileField('Json File')
    import_format = RadioField('Import Format', choices=[('text', 'text'), ('file', 'file')], default='text')

app/main/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
try:
    from urlparse import urljoin
except ImportError:
    from urllib.parse import urljoin
from datetime import datetime, timedelta

from flask import request, redirect, render_template, url_for, abort, flash, g, session
from flask import current_app, make_response
from flask.views import MethodView

# from flask.ext.login import login_required, current_user
from flask_login import login_required, current_user

from werkzeug.contrib.atom import AtomFeed
from mongoengine.queryset.visitor import Q


from . import models, signals, forms
from accounts.models import User
from accounts.permissions import admin_permission, editor_permission, writer_permission, reader_permission
from OctBlog.config import OctBlogSettings


PER_PAGE = OctBlogSettings['pagination'].get('per_page', 10)
ARCHIVE_PER_PAGE = OctBlogSettings['pagination'].get('archive_per_page', 10)
BACKGROUND = OctBlogSettings['background_image']
DAOVOICE = OctBlogSettings['daovoice']


def get_base_data():
    pages = models.Post.objects.filter(post_type='page', is_draft=False)
    blog_meta = OctBlogSettings['blog_meta']
    data = {
        'blog_meta': blog_meta,
        'pages': pages,
        'bg_home': BACKGROUND['home'],
        'bg_post': BACKGROUND['post'],
        'bg_about': BACKGROUND['about'],
        'qiniu': BACKGROUND['qiniu'],
        'allow_daovoice': DAOVOICE['allow_daovoice'],
        'dao_app_id': DAOVOICE['app_id'],
        }
    return data

def index():
    return 'Hello'

def list_posts():
    # Not compatible with old post model, deprecated
    # posts = models.Post.objects.filter(post_type='post', is_draft=False, weight__gt=0).order_by('-weight', '-pub_time')
    posts = models.Post.objects.filter(post_type='post', is_draft=False).order_by('-weight', '-pub_time')
    # Compatible with old post model, recommended
    posts = posts.filter(Q(weight__gt=0) | Q(weight=None))

    tags = posts.distinct('tags')

    try:
        cur_page = int(request.args.get('page', 1))
    except ValueError:
        cur_page = 1


    cur_category = request.args.get('category')
    cur_tag = request.args.get('tag')
    keywords = request.args.get('keywords')


    if keywords:
        # posts = posts.filter(raw__contains=keywords )
        posts = posts.filter(Q(raw__icontains=keywords) | Q(title__icontains=keywords))

    if cur_category:
        posts = posts.filter(category=cur_category)

    if cur_tag:
        posts = posts.filter(tags=cur_tag)


    #group by aggregate
    category_cursor = models.Post._get_collection().aggregate([
            { '$group' :
                { '_id' : {'category' : '$category' },
                  'name' : { '$first' : '$category' },
                  'count' : { '$sum' : 1 },
                }
            }
        ])

    widgets = models.Widget.objects(allow_post_types='post')




    posts = posts.paginate(page=cur_page, per_page=PER_PAGE)

    data = get_base_data()
    data['posts'] = posts
    data['cur_category'] = cur_category
    data['category_cursor'] = category_cursor
    data['cur_tag'] = cur_tag
    data['tags'] = tags
    data['keywords'] = keywords
    data['widgets'] = widgets

    return render_template('main/index.html', **data)

def list_wechats():
    posts = models.Post.objects.filter(post_type='wechat', is_draft=False).order_by('-pub_time')

    tags = posts.distinct('tags')

    try:
        cur_page = int(request.args.get('page', 1))
    except ValueError:
        cur_page = 1


    cur_tag = request.args.get('tag')
    keywords = request.args.get('keywords')


    if keywords:
        # posts = posts.filter(raw__contains=keywords )
        posts = posts.filter(Q(raw__icontains=keywords) | Q(title__icontains=keywords))


    if cur_tag:
        posts = posts.filter(tags=cur_tag)


    posts = posts.paginate(page=cur_page, per_page=PER_PAGE)

    widgets = models.Widget.objects(allow_post_types='wechat')

    data = get_base_data()
    data['posts'] = posts
    data['cur_tag'] = cur_tag
    data['tags'] = tags
    data['keywords'] = keywords
    data['widgets'] = widgets

    return render_template('main/wechat_list.html', **data)

def post_detail(slug, post_type='post', fix=False, is_preview=False):
    if is_preview:
        if not g.identity.can(reader_permission):
            abort(401)
        post = models.Draft.objects.get_or_404(slug=slug, post_type=post_type)
    else:
        post = models.Post.objects.get_or_404(slug=slug, post_type=post_type) if not fix else models.Post.objects.get_or_404(fix_slug=slug, post_type=post_type)

    # this block is abandoned
    if post.is_draft and current_user.is_anonymous:
        abort(404)

    data = get_base_data()
    data['post'] = post
    data['post_type'] = post_type

    if request.form:
        form = forms.CommentForm(obj=request.form)
    else:
        obj = {'author': session.get('author'), 'email': session.get('email'),'homepage': session.get('homepage'),}
        form = forms.CommentForm(**obj)
        # print session.get('email')
        if not current_user.is_anonymous:
            session['author'] = session.get('author') or current_user.username
            session['email'] = session.get('email') or current_user.email
            session['homepage'] = session.get('homepage') or current_user.homepage_url


    if request.form.get('oct-comment') and form.validate_on_submit():
        octblog_create_comment(form, post)
        url = '{0}#comment'.format(url_for('main.post_detail', slug=slug))
        url = '{0}#comment'.format(request.full_path)
        msg = 'Succeed to comment, and it will be displayed when the administrator reviews it.'
        flash(msg, 'success')
        return redirect(url)

    data['allow_donate'] = OctBlogSettings['donation']['allow_donate']
    data['donation_msg'] = OctBlogSettings['donation']['donation_msg']
    data['donation_img_url'] = OctBlogSettings['donation']['donation_img_url']

    data['display_wechat'] = OctBlogSettings['wechat']['display_wechat']
    data['wechat_msg'] = OctBlogSettings['wechat']['wechat_msg']
    data['wechat_image_url'] = OctBlogSettings['wechat']['wechat_image_url']
    data['wechat_title'] = OctBlogSettings['wechat']['wechat_title']

    data['display_copyright'] = OctBlogSettings['copyright']['display_copyright']
    data['copyright_msg'] = OctBlogSettings['copyright']['copyright_msg']

    data['allow_comment'] = OctBlogSettings['blog_comment']['allow_comment']
    if data['allow_comment']:
        comment_type = OctBlogSettings['blog_comment']['comment_type']
        comment_shortname = OctBlogSettings['blog_comment']['comment_opt'][comment_type]
        comment_func = get_comment_func(comment_type)

        

        data['comment_html'] = comment_func(slug, post.title, request.base_url, comment_shortname, form=form) if comment_func else ''

    data['allow_share_article'] = OctBlogSettings['allow_share_article']

    # send signal
    if not is_preview:
        signals.post_visited.send(current_app._get_current_object(), post=post)

    templates = {
        'post': 'main/post.html',
        'page': 'main/post.html',
        'wechat': 'main/wechat_detail.html',
    }

    return render_template(templates[post_type], **data)

def post_preview(slug, post_type='post'):
    return post_detail(slug=slug, post_type=post_type, is_preview=True)

def post_detail_general(slug, post_type):
    is_preview = request.args.get('is_preview', 'false')
    is_preview = True if is_preview.lower()=='true' else False
    return post_detail(slug=slug, post_type=post_type, is_preview=is_preview)

def author_detail(username):
    author = User.objects.get_or_404(username=username)

    posts = models.Post.objects.filter(post_type='post', is_draft=False, author=author).order_by('-pub_time')
    cur_page = request.args.get('page', 1)

    posts = posts.paginate(page=int(cur_page), per_page=ARCHIVE_PER_PAGE)

    data = get_base_data()
    data['user'] = author
    data['posts'] = posts
    # data['category_cursor'] = category_cursor
    # data['cur_tag'] = cur_tag
    # data['tags'] = tags
    # data['keywords'] = keywords

    return render_template('main/author.html', **data)


def get_comment_func(comment_type):
    # if comment_type == 'duoshuo':
    #     return duoshuo_comment
    # else:
    #     return None
    comment_func = {
        'octblog': octblog_comment,
        'duoshuo': duoshuo_comment,
    }

    return comment_func.get(comment_type)

def octblog_comment(post_id, post_title, post_url, comment_shortname, form=None, *args, **kwargs):
    template_name = 'main/comments.html'
    comments = models.Comment.objects(post_slug=post_id, status='approved').order_by('pub_time')
    # print comments[0].get_gavatar_url()
    # if not form:
    #     if session.get('author'):
    #         print 'session'
    #         return 'session'
    #         data = {'author': session['author'], 'email': session['email'],'homepage': session['homepage'],}
    #         form = forms.SessionCommentForm(obj=data)
    #     else:
    #         print 'no session'
    #         return 'no session'
    #         form = forms.CommentForm(obj=request.form)
    data = {
        'form': form,
        'comments': comments,
        'slug': post_id,
    }
    return render_template(template_name, **data)

def octblog_create_comment(form, post):
    comment = models.Comment()
    comment.author = form.author.data.strip()
    comment.email = form.email.data.strip()
    comment.homepage = form.homepage.data.strip() or None
    comment.post_slug = post.slug
    comment.post_title = post.title
    comment.md_content = form.content.data.strip()
    comment.save()

    session['author'] = form.author.data.strip()
    session['email'] = form.email.data.strip()
    session['homepage'] = form.homepage.data.strip()


def duoshuo_comment(post_id, post_title, post_url, duoshuo_shortname, *args, **kwargs):
    '''
    Create duoshuo script by params
    '''

app/templates/main/comments.html
<a name="comment"></a>
<h3>Comments</h3><br>

{% import "_msg.html" as messages %}
{{ messages.render_msg() }}

{% import "_form.html" as forms %}
<form method="POST" action="#comment">
    {{ forms.render(form) }}
    <button type="submit" class="btn btn-primary" name="oct-comment" value="oct-comment">Submit</button>
</form>
<br>

<table>
    {% for comment in comments %}
    <tr>
        <td style="width: 8%">
            <!-- <img class="media-object" src="http://7tsygu.com1.z0.glb.clouddn.com/user-avatar.jpg" alt="user-avatar"> -->
            <img class="media-object" src="{{ comment.get_gavatar_url() }}" alt="user-avatar">
        </td>
        <td>
            <h4>{{ comment.author }} 
                {% if comment.homepage %}
                    <a href="{{ comment.homepage }}" rel="nofollow" target="_blank"><i class="fa fa-home" aria-hidden="true"></i></a>
                {% endif %}
            </h4>
            <div>
                {{ comment.html_content|safe }} 
            </div>
        </td>
        <td style="width: 5%">
            <small>{{ comment.pub_time.strftime('%Y/%m/%d') }}</small>
        </td>
    </tr>
    {% endfor %}
</table>

app/templates/main/index.html
{% extends 'base.html' %}

{% block title %}{{ blog_meta.name }}{% endblock %}
{% block header %}
<!-- <header class="intro-header" style="background-image: url('http://7d9q7a.com1.z0.glb.clouddn.com/mayblog-home-bg.jpg')"> -->
<header class="intro-header" style="background-image: url({{ bg_home }})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>{{ blog_meta.name }}</h1>
                        <hr class="small">
                        <span class="subheading">{{ blog_meta.subtitle }} <a href="{{ url_for('main.recent_feed') }}"><i class="fa fa-rss"></i></a></span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col-lg-6 col-lg-offset-2 col-md-8 col-md-offset-1">
            {% for post in posts.items %}
            <div class="post-preview">
                <a href="{{ url_for('main.post_detail', slug=post.slug) }}">
                    <h2 class="post-title">
                        {{ post.title }}
                    </h2>
                </a>
                <p class="post-subtitle">
                    {{ post.abstract }}
                </p>
                <p class="post-meta">Posted by <a href="{{ url_for('main.author_detail', username=post.author.username) }}">{{ post.author.display_name }}</a> on {{ moment(post.pub_time).format('YYYY/MM/DD, h:mm a') }}</p>
                <p class="post-meta">category: <a href="?category={{ post.category }}">{{ post.category }}</a></p>
                <p class="post-meta">Tags:
                            {% for tag in post.tags %} <a href="{{ url_for('main.index') }}?tag={{ tag }}">{{ tag }}</a>  {% endfor %}
                </p>
            </div>
            {% if not loop.last %}
            <hr>
            {% endif %}
            {% else %}
                <p class="post-subtitle">
                    No articles found here
                </p>
            {% endfor %}
            <!-- Pager -->
            <ul class="pager">
                {% if posts.has_next %}
                <li class="next">
                    <a href="?page={{ posts.next_num }}
                        {%- if cur_category %}&category={{ cur_category }}{% endif %}
                        {%- if cur_tag %}&tag={{ cur_tag }}{% endif %}">Older Posts &rarr;</a>
                </li>
                {% endif %}
                {% if posts.has_prev %}
                    <li class="next"><a href="?page={{ posts.prev_num }}
                        {%- if cur_category %}&category={{ cur_category }}{% endif %}
                        {%- if keywords %}&keywords={{ keywords }}{% endif %}
                        {%- if cur_tag %}&tag={{ cur_tag }}{% endif %}">Previous Posts</a></li>
                {% endif %}
            </ul>
        </div>
        

        <div class="col-lg-3 col-md-2">
            <h3>Search</h3><hr/>
            <form id="search-form">
              <div class="form-group">
                <div class="input-group">
                  <div class="input-group-addon"><i class="fa fa-search"></i></div>
                  <input type="text" class="form-control" id="search" name="keywords" placeholder="search" value="{% if keywords %}{{ keywords }}{% endif %}">
                </div>
              </div>
              <!-- <button type="submit" class="btn btn-default">Transfer cash</button> -->
            </form>
            <!-- <hr> -->
            <br>

            <h3>Tags</h3><hr/>
            {% for tag in tags %}
                <a href="?tag={{tag}}" class="post-tag">
                    {% if tag == cur_tag %}
                    <span class="label label-primary">
                        {{ tag }}
                        <small><span class="glyphicon glyphicon-remove small rm-filter" aria-hidden="true"></span></small>
                    </span>
                    
                    {% else %}
                    <span class="label label-default">
                        {{ tag }}
                    </span>
                    
                    {% endif %}
                    
                </a>
                &nbsp;
            {% endfor %}

            
            <h3>Category</h3><hr/>
            <div class="list-group">
                {% for category in category_cursor %}
                {% if category and category.name %}
                    {% if cur_category == category.name %}
                        <a href="?category={{ category.name }}" class="list-group-item category-list active">{{ category.name }} 
                        <small><span class="glyphicon glyphicon-remove small rm-filter" aria-hidden="true"></span></small>
                        <span class="badge">&nbsp;{{ category.count }}&nbsp;</span></a>
                    {% else %}
                        <a href="?category={{ category.name }}" class="list-group-item category-list ">{{ category.name }} 
                        <span class="badge">&nbsp;{{ category.count }}&nbsp;</span></a>
                    {% endif %}
                {% endif %}
                {% endfor %}
            </div>


            {% for widget in widgets %}
            <h3>{{ widget.title | safe }}</h3><hr/>
            <div class="list-group">
                {{ widget.html_content | safe }}
            </div>
            {% endfor %}
                        
        </div>
    </div>
</div>

<hr>
{% endblock %}

{% block js %}
{{ moment.include_moment(local_js="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment-with-locales.min.js") }}
<script type="text/javascript">
$('.rm-filter').on('click', function (event) {

    location.href = "/";
    return false;
  });
</script>
{% endblock %}

app/templates/main/post.html
{% extends 'base.html' %}
{% block title %} {{ post.title }} {% endblock %}

{% block custom_head %}
    <link href="{{ url_for('static', filename='css/share.min.css') }}" rel="stylesheet">
{% endblock %}

{% block header %}
<!-- <header class="intro-header" style="background-image: url('http://7d9q7a.com1.z0.glb.clouddn.com/mayblog-home-bg.jpg')"> -->
<header class="intro-header" style="background-image: url({{ bg_post }})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1>{{ post.title }}</h1>
                        <!-- <h2 class="subheading">Problems look mighty small from 150 miles up</h2> -->
                        <span class="meta">Posted by <a href="{{ url_for('main.author_detail', username=post.author.username) }}">{{ post.author.display_name }}</a> on {{ moment(post.pub_time).format('YYYY/MM/DD, h:mm a') }}</span>
                        {% if post.category%}
                        <span class="meta">Category:
                            <a href="{{ url_for('main.index') }}?category={{ post.category }}">{{ post.category }}</a></span>
                        {% endif %}
                        <span class="meta">Tags:
                            {% for tag in post.tags %} <a href="{{ url_for('main.index') }}?tag={{ tag }}">{{ tag }}</a>  {% endfor %}
                        </span>
                        {% if g.identity.allow_edit or post.author==current_user%}
                        <span class="meta">
                            <!-- <br> -->
                            <a href="{{ url_for('blog_admin.edit_post', slug=post.slug) }}"><i class="fa fa-pencil"></i></a>
                        </span>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}
{% block main %}
<div class="container">
    <article>
        <!-- <div class="container"> -->
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    {{post.content_html|safe}}
                </div>
            </div>

        {% if not post.post_type=='page' %}
            {% if display_copyright %}
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <hr>
                    <p><strong>{{ copyright_msg }}</strong></p>
                <hr>
                </div>

            </div>
            {% endif %}
            <br>
            {% if allow_share_article %}
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="share-component" data-sites="weibo,wechat,douban,twitter,qq,google,facebook,linkedin"></div>
                </div>

            </div>
            {% endif %}
            <br>
            {% if allow_donate %}
            <div class="row">
                <!-- donate -->
                <div class ="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <p>{{ donation_msg }}</p>
                    <a id="btn_donate" class="btn_donate" href="#" title="Donate">
                    <i class="fa fa-usd"></i> | <i class="fa fa-jpy"></i>
                    </a>                  
                    <br>
                  <!-- weixin -->
                  <div id="donate_guide" class="donate_bar center ">
                      <img src="{{ donation_img_url }}" title="Donate">
                  </div> 
                </div>
                <!-- donate --> 
                
            </div>
            <br>
            {% endif %}

            {% if display_wechat %}
            <div class="row">
                <!-- donate -->
                <div class ="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <p>{{ wechat_msg }} <i class="fa fa-weixin" aria-hidden="true"></i></p>
                    <img src="{{ wechat_image_url }}" title="{{ wechat_title }}">
                </div>
                
            </div>
            {% endif %}
            
        {% endif %}
            
        <!-- </div> -->
    </article>
    <br>
    <hr>
    {% if allow_comment %}
        <article>
            <!-- <div class="container"> -->
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                        {{ comment_html|safe }}
                    </div>
                </div>
            <!-- </div> -->
        </article>
    {% endif %}
</div>
{% endblock %}

{% block js %}
{{ moment.include_moment(local_js="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment-with-locales.min.js") }}
<script src="{{ url_for('static', filename='js/share.min.js') }}"></script>
<script type="text/javascript">
    $('table').addClass('table');
    $('#btn_donate').on('click', function(event){
        if($('#donate_guide').hasClass('hidden'))
            $('#donate_guide').removeClass('hidden');
        else
            $('#donate_guide').addClass('hidden');
        return false
    });
    
    
</script>
{% endblock %}