app/accounts/urls.py
from flask import Blueprint

from . import views
from main import errors

accounts = Blueprint('accounts', __name__)

accounts.add_url_rule('/login/', 'login', views.login, methods=['GET', 'POST'])
accounts.add_url_rule('/logout/', 'logout', views.logout)
accounts.add_url_rule('/registration/', 'register', views.register, methods=['GET', 'POST'])
accounts.add_url_rule('/registration/su', 'register_su', views.register, defaults={'create_su':True}, methods=['GET', 'POST'])
accounts.add_url_rule('/add-user/', 'add_user', views.add_user, methods=['GET', 'POST'])
accounts.add_url_rule('/users/', view_func=views.Users.as_view('users'))
accounts.add_url_rule('/users/edit/<username>', view_func=views.User.as_view('edit_user'))
accounts.add_url_rule('/su-users/', view_func=views.SuUsers.as_view('su_users'))
accounts.add_url_rule('/su-users/edit/<username>', view_func=views.SuUser.as_view('su_edit_user'))
accounts.add_url_rule('/user/settings/', view_func=views.Profile.as_view('settings'))
accounts.add_url_rule('/user/password/', view_func=views.Password.as_view('password'))
accounts.add_url_rule('/user/email-confirm/<token>/', view_func=views.ConfirmEmail.as_view('confirm_email'))
accounts.add_url_rule('/user/reset-password/', view_func=views.ResetPasswordRequest.as_view('reset_password_request'))
accounts.add_url_rule('/user/reset-password/<token>/', view_func=views.ResetPassword.as_view('reset_password'))

accounts.errorhandler(403)(errors.handle_forbidden)

app/main/urls.py
from flask import Blueprint, g

from . import views, admin_views, errors
from OctBlog.config import OctBlogSettings

main = Blueprint('main', __name__)

main.add_url_rule('/', 'index', views.list_posts)
main.add_url_rule('/posts/', 'posts', views.list_posts)
main.add_url_rule('/wechats/', 'wechats', views.list_wechats)
main.add_url_rule('/posts/<slug>/', 'post_detail', views.post_detail, methods=['GET', 'POST'])
main.add_url_rule('/post/<slug>/', 'post_detail_fix', views.post_detail, defaults={'fix':True})
main.add_url_rule('/posts/<slug>/preview/', 'post_preview', views.post_detail, defaults={'is_preview':True})
main.add_url_rule('/posts/<slug>/<post_type>/preview/', 'post_general_preview', views.post_detail_general)
main.add_url_rule('/pages/<slug>/', 'page_detail', views.post_detail, defaults={'post_type':'page'}, methods=['GET', 'POST'])
main.add_url_rule('/wechats/<slug>/', 'wechat_detail', views.post_detail, defaults={'post_type':'wechat'})
main.add_url_rule('/archive/', 'archive', views.archive)
main.add_url_rule('/users/<username>/', 'author_detail', views.author_detail)
main.add_url_rule('/atom/', 'recent_feed', views.recent_feed)
main.add_url_rule('/sitemap.xml/', 'sitemap', views.sitemap)
main.errorhandler(404)(errors.page_not_found)
main.errorhandler(401)(errors.handle_unauthorized)
main.add_url_rule('/<path:invalid_path>', 'handle_unmatchable', errors.handle_unmatchable)


blog_admin = Blueprint('blog_admin', __name__)

blog_admin.add_url_rule('/', view_func=admin_views.AdminIndex.as_view('index'))

blog_admin.add_url_rule('/posts/', view_func=admin_views.PostsList.as_view('posts'))
blog_admin.add_url_rule('/posts/draft/', view_func=admin_views.DraftList.as_view('drafts'))
blog_admin.add_url_rule('/new-post/', view_func=admin_views.Post.as_view('new_post'))
blog_admin.add_url_rule('/posts/<slug>/', view_func=admin_views.Post.as_view('edit_post'))

blog_admin.add_url_rule('/pages/', view_func=admin_views.PostsList.as_view('pages'), defaults={'post_type':'page'})
blog_admin.add_url_rule('/pages/draft/', view_func=admin_views.DraftList.as_view('page_drafts'), defaults={'post_type':'page'})
blog_admin.add_url_rule('/new-page/', view_func=admin_views.Post.as_view('new_page'), defaults={'post_type':'page'})

blog_admin.add_url_rule('/wechats/', view_func=admin_views.PostsList.as_view('wechats'), defaults={'post_type':'wechat'})
blog_admin.add_url_rule('/wechats/draft/', view_func=admin_views.DraftList.as_view('wechat_drafts'), defaults={'post_type':'wechat'})
blog_admin.add_url_rule('/new-wechat/', view_func=admin_views.Post.as_view('new_wechat'), defaults={'post_type':'wechat'})

blog_admin.add_url_rule('/posts/statistics/', view_func=admin_views.PostStatisticList.as_view('post_statistics'))
blog_admin.add_url_rule('/posts/statistics/<slug>/', view_func=admin_views.PostStatisticDetail.as_view('post_statistics_detail'))

blog_admin.add_url_rule('/posts/comments/', view_func=admin_views.Comment.as_view('comments'))
blog_admin.add_url_rule('/posts/comments/approved/', view_func=admin_views.Comment.as_view('comments_approved'), defaults={'status':'approved'})
blog_admin.add_url_rule('/posts/comments/spam/', view_func=admin_views.Comment.as_view('comments_spam'), defaults={'status':'spam'})
blog_admin.add_url_rule('/posts/comments/<pk>/action/', view_func=admin_views.Comment.as_view('comment_action'))
blog_admin.add_url_rule('/posts/comments/import/', view_func=admin_views.ImportCommentView.as_view('import_comments'))
blog_admin.add_url_rule('/posts/comments/action/', view_func=admin_views.Comments.as_view('comments_action'))

blog_admin.add_url_rule('/su/posts/', view_func=admin_views.SuPostsList.as_view('su_posts'))
blog_admin.add_url_rule('/su/posts/<slug>/', view_func=admin_views.SuPost.as_view('su_post_edit'))
blog_admin.add_url_rule('/su/widgets/', view_func=admin_views.WidgetList.as_view('su_widgets'))
blog_admin.add_url_rule('/su/widgets/create/', view_func=admin_views.Widget.as_view('su_widget'))
blog_admin.add_url_rule('/su/widgets/<pk>/', view_func=admin_views.Widget.as_view('su_widget_edit'))
blog_admin.add_url_rule('/su/export/', view_func=admin_views.SuExportView.as_view('su_export'))

blog_admin.errorhandler(404)(errors.admin_page_not_found)
blog_admin.errorhandler(401)(errors.handle_unauthorized)
blog_admin.errorhandler(403)(errors.handle_forbidden)

ALLOW_WECHAT_PORT = OctBlogSettings['allow_wechat_port']

@blog_admin.before_app_request
def before_request():
    g.allow_wechat_port = ALLOW_WECHAT_PORT


app/accounts/models.py
from __future__ import unicode_literals
import datetime
from flask import current_app
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import TimedJSONWebSignatureSerializer
from OctBlog import db, login_manager

# ROLES = ('admin', 'editor', 'writer', 'reader')
ROLES = (('admin', 'admin'),
            ('editor', 'editor'),
            ('writer', 'writer'),
            ('reader', 'reader'))
SOCIAL_NETWORKS = {
    'weibo': {'fa_icon': 'fa fa-weibo', 'url': None},
    'weixin': {'fa_icon': 'fa fa-weixin', 'url': None},
    'twitter': {'fa_icon': 'fa fa fa-twitter', 'url': None},
    'github': {'fa_icon': 'fa fa-github', 'url': None},
    'facebook': {'fa_icon': 'fa fa-facebook', 'url': None},
    'linkedin': {'fa_icon': 'fa fa-linkedin', 'url': None},
}

class User(UserMixin, db.Document):
    username = db.StringField(max_length=255, required=True)
    email = db.EmailField(max_length=255)
    password_hash = db.StringField(required=True)
    create_time = db.DateTimeField(default=datetime.datetime.now, required=True)
    last_login = db.DateTimeField(default=datetime.datetime.now, required=True)
    is_email_confirmed = db.BooleanField(default=False)
    # is_active = db.BooleanField(default=True)
    is_superuser = db.BooleanField(default=False)
    role = db.StringField(max_length=32, default='reader', choices=ROLES)
    display_name = db.StringField(max_length=255, default=username)
    biography = db.StringField()
    social_networks = db.DictField(default=SOCIAL_NETWORKS)
    homepage_url = db.URLField()

    confirm_email_sent_time = db.DateTimeField()

    @property
    def password(self):
        raise AttributeError('password is not a readle attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def generate_confirmation_token(self, expiration=3600):
        serializer = TimedJSONWebSignatureSerializer(current_app.config['SECRET_KEY'], expiration)
        return serializer.dumps({'confirm':self.username})

    def confirm_email(self, token, expiration=3600):
        s = TimedJSONWebSignatureSerializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except Exception:
            return False
        if data.get('confirm') != self.username:
            return False
        self.is_email_confirmed = True
        self.save()
        return True

    def generate_reset_token(self, expiration=3600):
        serializer = TimedJSONWebSignatureSerializer(current_app.config['SECRET_KEY'], expiration)
        return serializer.dumps({'reset': self.username})

    @staticmethod
    def reset_password(token, new_password):
        serializer = TimedJSONWebSignatureSerializer(current_app.config['SECRET_KEY'])
        try:
            data = serializer.loads(token)
        except:
            return False

        try:
            user = User.objects.get(username=data.get('reset'))
        except Exception:
            return False

        user.password = new_password
        user.save()
        return True

    def get_id(self):
        try:
            # return unicode(self.username)
            return self.username

        except AttributeError:
            raise NotImplementedError('No `username` attribute - override `get_id`')

    def __unicode__(self):
        return self.username


    
@login_manager.user_loader
def load_user(username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        user = None
    return user

app/accounts/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SelectField, SubmitField, ValidationError
from wtforms.validators import Required, Length, Email, Regexp, EqualTo, URL, Optional, DataRequired
# from flask.ext.login import current_user
# from flask.ext.mongoengine.wtf import model_form
from flask_login import current_user
from flask_mongoengine.wtf import model_form

from . import models

class LoginForm(FlaskForm):
    username = StringField()
    password = PasswordField()
    remember_me = BooleanField('Keep me logged in')

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[Required(), Length(1,64), 
        Regexp('^[A-Za-z0-9_.]*$', 0, 'Usernames must have only letters, numbers dots or underscores')])
    email = StringField('Email', validators=[Required(), Length(1,128), Email()])
    password = PasswordField('Password', validators=[Required(), EqualTo('password2', message='Passwords must match')])
    password2 = PasswordField('Confirm password', validators=[Required()])

    def validate_username(self, field):
        if models.User.objects.filter(username=field.data).count() > 0:
            raise ValidationError('Username already in use')

    def validate_email(self, field):
        if models.User.objects.filter(email=field.data).count() > 0:
            raise ValidationError('Email already in registered')

class UserForm(FlaskForm):
    email = StringField('Email', validators=[Required(), Length(1,128), Email()])
    # is_active = BooleanField('Is activie')
    # is_superuser = BooleanField('Is superuser')
    role = SelectField('Role', choices=models.ROLES)

# SuUserForm = model_form(models.User, exclude=['create_time', 'last_login', 'password_hash'])

class SuUserForm(FlaskForm):
    email = StringField('Email', validators=[Required(), Length(1,128), Email()])
    is_superuser = BooleanField('Is superuser')
    is_email_confirmed = BooleanField('Is Email Confirmed') 
    role = SelectField('Role', choices=models.ROLES)
    display_name = StringField('Display Name', validators=[Length(1,128)])
    biography = StringField('Biograpyh')
    homepage_url = StringField('Homepage', validators=[URL(), Optional()])
    weibo = StringField('Weibo', validators=[URL(), Optional()])
    weixin = StringField('Weixin', validators=[Optional(), URL()])
    twitter = StringField('Twitter', validators=[URL(), Optional()])
    github = StringField('github', validators=[URL(), Optional()])
    facebook = StringField('Facebook', validators=[URL(), Optional()])
    linkedin = StringField('Linkedin', validators=[URL(), Optional()])

# ProfileForm = model_form(models.User, exclude=['username', 'password_hash', 'create_time', 'last_login', 
#     'is_email_confirmed', 'is_superuser', 'role'])
class ProfileForm(FlaskForm):
    email = StringField('Email', validators=[Required(), Length(1,128), Email()])
    display_name = StringField('Display Name', validators=[Length(1,128)])
    biography = StringField('Biograpyh')
    homepage_url = StringField('Homepage', validators=[URL(), Optional()])
    weibo = StringField('Weibo', validators=[URL(), Optional()])
    weixin = StringField('Weixin', validators=[Optional(), URL()])
    twitter = StringField('Twitter', validators=[URL(), Optional()])
    github = StringField('github', validators=[URL(), Optional()])
    facebook = StringField('Facebook', validators=[URL(), Optional()])
    linkedin = StringField('Linkedin', validators=[URL(), Optional()])

class PasswordForm(FlaskForm):
    current_password = PasswordField('Current Password', validators=[Required()])
    new_password = PasswordField('New Password', validators=[Required(), EqualTo('password2', message='Passwords must match')])
    password2 = PasswordField('Confirm password', validators=[Required()])

    def validate_current_password(self, field):
        if not current_user.verify_password(field.data):
            raise ValidationError('Current password is wrong')

class PasswordResetRequestForm(FlaskForm):
    email = StringField('Email', validators=[Required(), Length(1,128), Email()])

class PasswordResetForm(FlaskForm):
    password = PasswordField('New Password', validators=[DataRequired(), EqualTo('password2', message='Passwords must match')])
    password2 = PasswordField('Confirm password', validators=[DataRequired()])

app/templates/accounts/login.html
{% extends "admin_base.html" %}
{% block title %}Login{% endblock %}
{% block main %}

<div class="row">
    <div class="col-xs-6 col-sm-3"></div>
    <div class="col-xs-6 col-sm-6">
        {% import "_form.html" as forms %}
        <form method="POST" action="" id='login'>
        {{ forms.render(form) }}
            <button type="submit" class="btn btn-primary" name="login">Login</button>
        </form>
        <br>
        <!-- <br> -->
        <a href="{{ url_for('accounts.reset_password_request') }}"> <i class="fa fa-hand-o-right" aria-hidden="true"></i>
        Click here if you forget your password?</a>
    </div>
    <div class="col-xs-6 col-sm-3"></div>
</div>
{% endblock %}

app/templates/accounts/password.html
{% extends 'admin_base.html' %}
{% block title %} Settings: Change Password {% endblock %}

{% block main %}
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <ul class="nav nav-tabs">
          <li role="presentation"><a href="{{ url_for('accounts.settings' )}}">Profile</a></li>
          <li role="presentation" class="active"><a href="#" onclick="return false">Password</a></li>
        </ul>
    </div>
</div>
<br>
<div class="row">
    <div class="col-xs-6 col-sm-3"></div>
    <div class="col-xs-6 col-sm-6">
        {% import "_form.html" as forms %}
        <form method="POST" action="" id='password'>
        {{ forms.render(form) }}
            <button type="submit" class="btn btn-primary" name="update" value="update">Update</button>
        </form>

        <hr>

        {% if user.is_email_confirmed %}
            <blockquote>
                <p>Your email has been confirmed!</p>
            </blockquote>
        {% else %}
            <form method="POST" action="" id='confirm_email'>
                {% if email_resend_flag %}
                    {% set msg = 'Your confirmation email has been sent, click the button to resend email' %}
                    {% set button = 'Resend email' %}
                {% else %}
                    {% set msg = 'Click the button to send confirmation email' %}
                    {% set button = 'Confirm email' %}
                {% endif %}
                <blockquote><p>{{ msg }}</p>
                <button type="submit" class="btn btn-primary" name="email" value="email">{{ button }}</button>
                </blockquote>
            </form>
        {% endif %}

    </div>
</div>

{% endblock %}

app/templates/accounts/registration.html
{% extends "admin_base.html" %}
{% block title %}Registration{% endblock %}
{% block main %}

<div class="row">
    <div class="col-xs-6 col-sm-3"></div>
    <div class="col-xs-6 col-sm-6">
        {% import "_form.html" as forms %}
        <form method="POST" action="" id='login'>
        {{ forms.render(form) }}
            <button type="submit" class="btn btn-primary" name="register">Register</button>
        </form>
    </div>
    <div class="col-xs-6 col-sm-3"></div>
</div>
{% endblock %}

app/templates/accounts/reset_password.html
{% extends "admin_base.html" %}
{% block title %}Reset Password{% endblock %}
{% block main %}

<div class="row">
    <div class="col-xs-6 col-sm-3"></div>
    <div class="col-xs-6 col-sm-6">
        {% import "_form.html" as forms %}
        <form method="POST" action="" id='reset'>
        {{ forms.render(form) }}
            <button type="submit" class="btn btn-primary" name="reset">Reset Password</button>
        </form>
    </div>
    <div class="col-xs-6 col-sm-3"></div>
</div>
{% endblock %}

app/templates/accounts/settings.html
{% extends 'admin_base.html' %}
{% block title %} Settings: Update Profile {% endblock %}

{% block main %}
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <ul class="nav nav-tabs">
          <li role="presentation" class="active"><a href="#" onclick="return false">Profile</a></li>
          <li role="presentation"><a href="{{ url_for('accounts.password') }}">Password</a></li>
        </ul>
    </div>
</div>
<br>
<div class="row">
    <div class="col-xs-6 col-sm-3"></div>
    <div class="col-xs-6 col-sm-6">
        {% import "_form.html" as forms %}
        <form method="POST" action="" id='profile'>
        {{ forms.render(form) }}
            <button type="submit" class="btn btn-primary" name="update">Update</button>
        </form>
    </div>
    <div class="col-xs-6 col-sm-3"></div>
</div>
{% endblock %}

app/templates/accounts/su_users.html
{% extends 'admin_base.html' %}

{% block title %}Users{% endblock %}
{% block main %}
<div class="row">
    <div class="col-md-10">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No.</th>
                <th>Username</th>
                <th>Email</th>
                <th>Is Active</th>
                <th>Email Confirmed</th>
                <th>Is Superuser</th>
                <th>Actions</th>
            </tr>
    </thead>
    <tbody>
    {% for user in users %}
        <tr id="user-{{ user.username }}">
            <td>{{ loop.index }}</td>
            <td><a href="{{ url_for('accounts.su_edit_user', username=user.username) }}">{{ user.username }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.is_active }}</td>
            <td>{{ user.is_email_confirmed }}</td>
            <td>{{ user.is_superuser }}</td>
            <td>
                <a href="{{ url_for('accounts.su_edit_user', username=user.username) }}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a>
            </td>
        </tr>
        {% else %}
        <tr><td colspan="7">No user yet</td></tr>
    {% endfor %}     
    </tbody>
    </table>

    </div>
    <div class="col-md-2">
        <!-- <h4>Filter By Group</h4> -->
        <p><strong>Filter By Role</strong></p>
        <hr>
        <div class="list-group">
          Not yet
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
{% endblock %}

app/templates/accounts/user.html
{% extends 'admin_base.html' %}
{% block title %} Edit User {% endblock %}

{% block main %}
<div class="row">
    <div class="col-md-6 col-md-offset-1">
        <h3>User Details</h3>
        <hr>
        {% import "_form.html" as forms %}
        <form method="POST" action="">
            {{ forms.render(form) }}
            {% if g.identity.allow_su %}
            <div class="checkbox">
                <label>
                  <input type="checkbox" name='is_superuser' {%if user.is_superuser %}checked{% endif %}> Is Superuser
                </label>
                <br>
                <label>
                  <input type="checkbox" name='is_email_confirmed' {%if user.is_email_confirmed %}checked{% endif %}> Is Email Confirmed
                </label>
            </div>
            {% endif %}
            <button type="submit" class="btn btn-primary" name="user" value="user">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

app/templates/accounts/users.html
{% extends 'admin_base.html' %}

{% block title %}Users{% endblock %}
{% block main %}
<div class="row">
    <div class="col-md-10">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No.</th>
                <th>Username</th>
                <th>Email</th>
                <th>Is Active</th>
                <th>Last Login</th>
                <th>Create Date</th>
                <th>Actions</th>
            </tr>
    </thead>
    <tbody>
    {% for user in users %}
        <tr id="user-{{ user.username }}">
            <td>{{ loop.index }}</td>
            <td><a href="{{ url_for('accounts.edit_user', username=user.username) }}">{{ user.username }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.is_active }}</td>
            <td>{{ user.last_login.strftime('%Y/%m/%d %H:%M:%S') }}</td>
            <td>{{ user.create_time.strftime('%Y/%m/%d') }}</td>
            <td>
                <a href="{{ url_for('accounts.edit_user', username=user.username) }}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a>
                &nbsp
                <a href="{{ url_for('accounts.edit_user', username=user.username) }}"  class="del-user"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> </a>
            </td>
        </tr>
        {% else %}
        <tr><td colspan="7">No user yet</td></tr>
    {% endfor %}     
    </tbody>
    </table>

    </div>
    <div class="col-md-2">
        <!-- <h4>Filter By Group</h4> -->
        <p><strong>Filter By Role</strong></p>
        <hr>
        <div class="list-group">
          Not yet
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script type="text/javascript">
$('.del-user').on('click', function (event) {
    // var answer = confirm("Delete post?");
    // return answer;
    var url = $(this).attr('href');
    url = url + '?ajax=true';

    bootbox.confirm("Are you sure?", function(result) {
      if(result){
        // $.get(url, function(){
        //     location.reload();
        // });
        $.ajax({
            url: url,
            type: 'DELETE',
            success: function(result){
                location.reload();
            }

        });
        }
    });
    return false;
  });
</script>
{% endblock %}