app/main/urls.py
from flask import Blueprint, g

from . import views, admin_views, errors
from OctBlog.config import OctBlogSettings

main = Blueprint('main', __name__)

main.add_url_rule('/', 'index', views.list_posts)
main.add_url_rule('/posts/', 'posts', views.list_posts)
main.add_url_rule('/wechats/', 'wechats', views.list_wechats)
main.add_url_rule('/posts/<slug>/', 'post_detail', views.post_detail, methods=['GET', 'POST'])
main.add_url_rule('/post/<slug>/', 'post_detail_fix', views.post_detail, defaults={'fix':True})
main.add_url_rule('/posts/<slug>/preview/', 'post_preview', views.post_detail, defaults={'is_preview':True})
main.add_url_rule('/posts/<slug>/<post_type>/preview/', 'post_general_preview', views.post_detail_general)
main.add_url_rule('/pages/<slug>/', 'page_detail', views.post_detail, defaults={'post_type':'page'}, methods=['GET', 'POST'])
main.add_url_rule('/wechats/<slug>/', 'wechat_detail', views.post_detail, defaults={'post_type':'wechat'})
main.add_url_rule('/archive/', 'archive', views.archive)
main.add_url_rule('/users/<username>/', 'author_detail', views.author_detail)
main.add_url_rule('/atom/', 'recent_feed', views.recent_feed)
main.add_url_rule('/sitemap.xml/', 'sitemap', views.sitemap)
main.errorhandler(404)(errors.page_not_found)
main.errorhandler(401)(errors.handle_unauthorized)
main.add_url_rule('/<path:invalid_path>', 'handle_unmatchable', errors.handle_unmatchable)


blog_admin = Blueprint('blog_admin', __name__)

blog_admin.add_url_rule('/', view_func=admin_views.AdminIndex.as_view('index'))

blog_admin.add_url_rule('/posts/', view_func=admin_views.PostsList.as_view('posts'))
blog_admin.add_url_rule('/posts/draft/', view_func=admin_views.DraftList.as_view('drafts'))
blog_admin.add_url_rule('/new-post/', view_func=admin_views.Post.as_view('new_post'))
blog_admin.add_url_rule('/posts/<slug>/', view_func=admin_views.Post.as_view('edit_post'))

blog_admin.add_url_rule('/pages/', view_func=admin_views.PostsList.as_view('pages'), defaults={'post_type':'page'})
blog_admin.add_url_rule('/pages/draft/', view_func=admin_views.DraftList.as_view('page_drafts'), defaults={'post_type':'page'})
blog_admin.add_url_rule('/new-page/', view_func=admin_views.Post.as_view('new_page'), defaults={'post_type':'page'})

blog_admin.add_url_rule('/wechats/', view_func=admin_views.PostsList.as_view('wechats'), defaults={'post_type':'wechat'})
blog_admin.add_url_rule('/wechats/draft/', view_func=admin_views.DraftList.as_view('wechat_drafts'), defaults={'post_type':'wechat'})
blog_admin.add_url_rule('/new-wechat/', view_func=admin_views.Post.as_view('new_wechat'), defaults={'post_type':'wechat'})

blog_admin.add_url_rule('/posts/statistics/', view_func=admin_views.PostStatisticList.as_view('post_statistics'))
blog_admin.add_url_rule('/posts/statistics/<slug>/', view_func=admin_views.PostStatisticDetail.as_view('post_statistics_detail'))

blog_admin.add_url_rule('/posts/comments/', view_func=admin_views.Comment.as_view('comments'))
blog_admin.add_url_rule('/posts/comments/approved/', view_func=admin_views.Comment.as_view('comments_approved'), defaults={'status':'approved'})
blog_admin.add_url_rule('/posts/comments/spam/', view_func=admin_views.Comment.as_view('comments_spam'), defaults={'status':'spam'})
blog_admin.add_url_rule('/posts/comments/<pk>/action/', view_func=admin_views.Comment.as_view('comment_action'))
blog_admin.add_url_rule('/posts/comments/import/', view_func=admin_views.ImportCommentView.as_view('import_comments'))
blog_admin.add_url_rule('/posts/comments/action/', view_func=admin_views.Comments.as_view('comments_action'))

blog_admin.add_url_rule('/su/posts/', view_func=admin_views.SuPostsList.as_view('su_posts'))
blog_admin.add_url_rule('/su/posts/<slug>/', view_func=admin_views.SuPost.as_view('su_post_edit'))
blog_admin.add_url_rule('/su/widgets/', view_func=admin_views.WidgetList.as_view('su_widgets'))
blog_admin.add_url_rule('/su/widgets/create/', view_func=admin_views.Widget.as_view('su_widget'))
blog_admin.add_url_rule('/su/widgets/<pk>/', view_func=admin_views.Widget.as_view('su_widget_edit'))
blog_admin.add_url_rule('/su/export/', view_func=admin_views.SuExportView.as_view('su_export'))

blog_admin.errorhandler(404)(errors.admin_page_not_found)
blog_admin.errorhandler(401)(errors.handle_unauthorized)
blog_admin.errorhandler(403)(errors.handle_forbidden)

ALLOW_WECHAT_PORT = OctBlogSettings['allow_wechat_port']

@blog_admin.before_app_request
def before_request():
    g.allow_wechat_port = ALLOW_WECHAT_PORT


app/main/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
try:
    from urlparse import urljoin
except ImportError:
    from urllib.parse import urljoin
from datetime import datetime, timedelta

from flask import request, redirect, render_template, url_for, abort, flash, g, session
from flask import current_app, make_response
from flask.views import MethodView

# from flask.ext.login import login_required, current_user
from flask_login import login_required, current_user

from werkzeug.contrib.atom import AtomFeed
from mongoengine.queryset.visitor import Q


from . import models, signals, forms
from accounts.models import User
from accounts.permissions import admin_permission, editor_permission, writer_permission, reader_permission
from OctBlog.config import OctBlogSettings


PER_PAGE = OctBlogSettings['pagination'].get('per_page', 10)
ARCHIVE_PER_PAGE = OctBlogSettings['pagination'].get('archive_per_page', 10)
BACKGROUND = OctBlogSettings['background_image']
DAOVOICE = OctBlogSettings['daovoice']


def get_base_data():
    pages = models.Post.objects.filter(post_type='page', is_draft=False)
    blog_meta = OctBlogSettings['blog_meta']
    data = {
        'blog_meta': blog_meta,
        'pages': pages,
        'bg_home': BACKGROUND['home'],
        'bg_post': BACKGROUND['post'],
        'bg_about': BACKGROUND['about'],
        'qiniu': BACKGROUND['qiniu'],
        'allow_daovoice': DAOVOICE['allow_daovoice'],
        'dao_app_id': DAOVOICE['app_id'],
        }
    return data

def index():
    return 'Hello'

def list_posts():
    # Not compatible with old post model, deprecated
    # posts = models.Post.objects.filter(post_type='post', is_draft=False, weight__gt=0).order_by('-weight', '-pub_time')
    posts = models.Post.objects.filter(post_type='post', is_draft=False).order_by('-weight', '-pub_time')
    # Compatible with old post model, recommended
    posts = posts.filter(Q(weight__gt=0) | Q(weight=None))

    tags = posts.distinct('tags')

    try:
        cur_page = int(request.args.get('page', 1))
    except ValueError:
        cur_page = 1


    cur_category = request.args.get('category')
    cur_tag = request.args.get('tag')
    keywords = request.args.get('keywords')


    if keywords:
        # posts = posts.filter(raw__contains=keywords )
        posts = posts.filter(Q(raw__icontains=keywords) | Q(title__icontains=keywords))

    if cur_category:
        posts = posts.filter(category=cur_category)

    if cur_tag:
        posts = posts.filter(tags=cur_tag)


    #group by aggregate
    category_cursor = models.Post._get_collection().aggregate([
            { '$group' :
                { '_id' : {'category' : '$category' },
                  'name' : { '$first' : '$category' },
                  'count' : { '$sum' : 1 },
                }
            }
        ])

    widgets = models.Widget.objects(allow_post_types='post')




    posts = posts.paginate(page=cur_page, per_page=PER_PAGE)

    data = get_base_data()
    data['posts'] = posts
    data['cur_category'] = cur_category
    data['category_cursor'] = category_cursor
    data['cur_tag'] = cur_tag
    data['tags'] = tags
    data['keywords'] = keywords
    data['widgets'] = widgets

    return render_template('main/index.html', **data)

def list_wechats():
    posts = models.Post.objects.filter(post_type='wechat', is_draft=False).order_by('-pub_time')

    tags = posts.distinct('tags')

    try:
        cur_page = int(request.args.get('page', 1))
    except ValueError:
        cur_page = 1


    cur_tag = request.args.get('tag')
    keywords = request.args.get('keywords')


    if keywords:
        # posts = posts.filter(raw__contains=keywords )
        posts = posts.filter(Q(raw__icontains=keywords) | Q(title__icontains=keywords))


    if cur_tag:
        posts = posts.filter(tags=cur_tag)


    posts = posts.paginate(page=cur_page, per_page=PER_PAGE)

    widgets = models.Widget.objects(allow_post_types='wechat')

    data = get_base_data()
    data['posts'] = posts
    data['cur_tag'] = cur_tag
    data['tags'] = tags
    data['keywords'] = keywords
    data['widgets'] = widgets

    return render_template('main/wechat_list.html', **data)

def post_detail(slug, post_type='post', fix=False, is_preview=False):
    if is_preview:
        if not g.identity.can(reader_permission):
            abort(401)
        post = models.Draft.objects.get_or_404(slug=slug, post_type=post_type)
    else:
        post = models.Post.objects.get_or_404(slug=slug, post_type=post_type) if not fix else models.Post.objects.get_or_404(fix_slug=slug, post_type=post_type)

    # this block is abandoned
    if post.is_draft and current_user.is_anonymous:
        abort(404)

    data = get_base_data()
    data['post'] = post
    data['post_type'] = post_type

    if request.form:
        form = forms.CommentForm(obj=request.form)
    else:
        obj = {'author': session.get('author'), 'email': session.get('email'),'homepage': session.get('homepage'),}
        form = forms.CommentForm(**obj)
        # print session.get('email')
        if not current_user.is_anonymous:
            session['author'] = session.get('author') or current_user.username
            session['email'] = session.get('email') or current_user.email
            session['homepage'] = session.get('homepage') or current_user.homepage_url


    if request.form.get('oct-comment') and form.validate_on_submit():
        octblog_create_comment(form, post)
        url = '{0}#comment'.format(url_for('main.post_detail', slug=slug))
        url = '{0}#comment'.format(request.full_path)
        msg = 'Succeed to comment, and it will be displayed when the administrator reviews it.'
        flash(msg, 'success')
        return redirect(url)

    data['allow_donate'] = OctBlogSettings['donation']['allow_donate']
    data['donation_msg'] = OctBlogSettings['donation']['donation_msg']
    data['donation_img_url'] = OctBlogSettings['donation']['donation_img_url']

    data['display_wechat'] = OctBlogSettings['wechat']['display_wechat']
    data['wechat_msg'] = OctBlogSettings['wechat']['wechat_msg']
    data['wechat_image_url'] = OctBlogSettings['wechat']['wechat_image_url']
    data['wechat_title'] = OctBlogSettings['wechat']['wechat_title']

    data['display_copyright'] = OctBlogSettings['copyright']['display_copyright']
    data['copyright_msg'] = OctBlogSettings['copyright']['copyright_msg']

    data['allow_comment'] = OctBlogSettings['blog_comment']['allow_comment']
    if data['allow_comment']:
        comment_type = OctBlogSettings['blog_comment']['comment_type']
        comment_shortname = OctBlogSettings['blog_comment']['comment_opt'][comment_type]
        comment_func = get_comment_func(comment_type)

        

        data['comment_html'] = comment_func(slug, post.title, request.base_url, comment_shortname, form=form) if comment_func else ''

    data['allow_share_article'] = OctBlogSettings['allow_share_article']

    # send signal
    if not is_preview:
        signals.post_visited.send(current_app._get_current_object(), post=post)

    templates = {
        'post': 'main/post.html',
        'page': 'main/post.html',
        'wechat': 'main/wechat_detail.html',
    }

    return render_template(templates[post_type], **data)

def post_preview(slug, post_type='post'):
    return post_detail(slug=slug, post_type=post_type, is_preview=True)

def post_detail_general(slug, post_type):
    is_preview = request.args.get('is_preview', 'false')
    is_preview = True if is_preview.lower()=='true' else False
    return post_detail(slug=slug, post_type=post_type, is_preview=is_preview)

def author_detail(username):
    author = User.objects.get_or_404(username=username)

    posts = models.Post.objects.filter(post_type='post', is_draft=False, author=author).order_by('-pub_time')
    cur_page = request.args.get('page', 1)

    posts = posts.paginate(page=int(cur_page), per_page=ARCHIVE_PER_PAGE)

    data = get_base_data()
    data['user'] = author
    data['posts'] = posts
    # data['category_cursor'] = category_cursor
    # data['cur_tag'] = cur_tag
    # data['tags'] = tags
    # data['keywords'] = keywords

    return render_template('main/author.html', **data)


def get_comment_func(comment_type):
    # if comment_type == 'duoshuo':
    #     return duoshuo_comment
    # else:
    #     return None
    comment_func = {
        'octblog': octblog_comment,
        'duoshuo': duoshuo_comment,
    }

    return comment_func.get(comment_type)

def octblog_comment(post_id, post_title, post_url, comment_shortname, form=None, *args, **kwargs):
    template_name = 'main/comments.html'
    comments = models.Comment.objects(post_slug=post_id, status='approved').order_by('pub_time')
    # print comments[0].get_gavatar_url()
    # if not form:
    #     if session.get('author'):
    #         print 'session'
    #         return 'session'
    #         data = {'author': session['author'], 'email': session['email'],'homepage': session['homepage'],}
    #         form = forms.SessionCommentForm(obj=data)
    #     else:
    #         print 'no session'
    #         return 'no session'
    #         form = forms.CommentForm(obj=request.form)
    data = {
        'form': form,
        'comments': comments,
        'slug': post_id,
    }
    return render_template(template_name, **data)

def octblog_create_comment(form, post):
    comment = models.Comment()
    comment.author = form.author.data.strip()
    comment.email = form.email.data.strip()
    comment.homepage = form.homepage.data.strip() or None
    comment.post_slug = post.slug
    comment.post_title = post.title
    comment.md_content = form.content.data.strip()
    comment.save()

    session['author'] = form.author.data.strip()
    session['email'] = form.email.data.strip()
    session['homepage'] = form.homepage.data.strip()


def duoshuo_comment(post_id, post_title, post_url, duoshuo_shortname, *args, **kwargs):
    '''
    Create duoshuo script by params
    '''

app/templates/_form.html
{% macro render(form) -%}

{% for field in form %}
  {% if field.type in ['CSRFTokenField', 'HiddenField'] %}
    {{ field() }}
  {% elif field.type == "BooleanField" %}
  <div class="checkbox">
    <label>
      {{ field() }} {{ field.label }}
    </label>
  </div>

  {% elif field.type == "RadioField" %}
  {{ field.label }}
    {% for subfield in field %}
      <div class="radio">
        <label>{{ subfield }} {{ subfield.label }}</label>
      </div>
  {% endfor %}
    

  {% else %}
    <div class="clearfix {% if field.errors %}has-error{% endif %} form-group">

      {{ field.label }}
        {% if field.type == "TextAreaField" %}
          {{ field(class_="form-control", rows=10) }}
        {% else %}
          {{ field(class_="form-control") }}
        {% endif %}
        {% if field.errors or field.help_text %}
          <span class="help-block">
          {% if field.errors %}
            {{ field.errors|join(' ') }}
          {% else %}
            {{ field.help_text }}
          {% endif %}
          </span>
        {% endif %}
    </div>
  {% endif %}
{% endfor %}

{% endmacro %}

app/templates/_msg.html
{% macro render_msg() %}

{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <div class="flash_msg">
    {% for category, message in messages %}
      {% if category == 'message' %}
        {% set category='info' %}
      {% endif %}
      <div class="alert alert-{{ category }} alert-dismissible" role="alert" style="margin-bottom: 0px">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          {{ message }}
      </div>
    {% endfor %}
    </div>
  {% endif %}
{% endwith %}

{% endmacro %}

app/templates/_pagination.html
{% macro render_pagination(pagination) %}
  <nav>
    <ul class="pagination">
      {% if not pagination.has_prev %}
        <li class="disabled">
            <span aria-hidden="true">&laquo;</span>
        </li>
      {% else %}
        <li>
        <a href="?page={{ pagination.prev_num }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
        </li>
      {% endif %}
    
      {%- for page in pagination.iter_pages() %}
        {% if page %}
          {% if page != pagination.page %}
            <li><a href="?page={{ page }}">{{ page }}</a></li>
          {% else %}
            <li class="disabled"><a href="?page={{ page }}"><strong>{{ page }}</strong></a></li>
          {% endif %}
        {% else %}
          <!-- <span class=ellipsis>…</span> -->
          <li><a href="#">...</a></li>
        {% endif %}
      {%- endfor %}

      {% if not pagination.has_next %}
        <li class="disabled">
          <span aria-hidden="true">&raquo;</span>
        </li>
      {% else %}
        <li>
          <a href="?page={{ pagination.next_num }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% endif %}      
    </ul>
  </nav>
{% endmacro %}

app/templates/admin_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}Otc Blog Admin{% endblock %}</title>
    
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="96x96" href="{{ url_for('static', filename='img/favicon-96x96.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/favicon-16x16.png') }}">
    
    <!-- Bootstrap Core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/octblog.css') }}" rel="stylesheet">

    
    <!-- Custom CSS -->
    
    {% block css %}{% endblock %}
    <style> html{display : none ; } </style> 
    <script>
    if( self == top ) {
              document.documentElement.style.display = 'block' ;
       } else {
           top.location = self.location ;
       }
    </script>
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
{% import "_msg.html" as messages %}
{{ messages.render_msg() }}
    <!-- Navigation -->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('main.index') }}">Oct Blog</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="_active"><a href="{{ url_for('blog_admin.index') }}">Home <span class="sr-only">(current)</span></a></li>
            
            {% if g.identity.allow_write %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Posts <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('blog_admin.posts') }}">All Posts</a></li>
                <li><a href="{{ url_for('blog_admin.new_post') }}">New Post</a></li>
                <!-- <li><a href="{{ url_for('blog_admin.posts') }}?draft=true">Drafts</a></li> -->
                <li><a href="{{ url_for('blog_admin.drafts') }}">Drafts</a></li>
                <!-- <li class="divider"></li> -->

                <li class="divider"></li>
                <li><a href="#">Tags</a></li>
                <li><a href="#">Category</a></li>

                <li class="divider"></li>
                <li><a href="#">Import</a></li>
                <li><a href="#">Export</a></li>
              </ul>
            </li>

            {% if g.allow_wechat_port %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">WeChat <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('blog_admin.wechats') }}">All WeChats</a></li>
                <li><a href="{{ url_for('blog_admin.new_wechat') }}">New WeChat</a></li>
                <!-- <li><a href="{{ url_for('blog_admin.pages') }}?draft=true">Drafts</a></li> -->
                <li><a href="{{ url_for('blog_admin.wechat_drafts') }}">Drafts</a></li>
              </ul>
            </li>
            {% endif %} <!-- end allow_wechat_port -->

            
            {% endif %}  <!-- g.identity.allow_write -->

            {% if g.identity.allow_edit %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Pages <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('blog_admin.pages') }}">All Pages</a></li>
                <li><a href="{{ url_for('blog_admin.new_page') }}">New Page</a></li>
                <!-- <li><a href="{{ url_for('blog_admin.pages') }}?draft=true">Drafts</a></li> -->
                <li><a href="{{ url_for('blog_admin.page_drafts') }}">Drafts</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Comments <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('blog_admin.comments') }}">Pending</a></li>
                <li><a href="{{ url_for('blog_admin.comments_approved') }}">Approved</a></li>
                <!-- <li><a href="{{ url_for('blog_admin.pages') }}?draft=true">Drafts</a></li> -->
                <li><a href="{{ url_for('blog_admin.comments_spam') }}">Spam</a></li>
                <li class="divider"></li>
                <li><a href="{{ url_for('blog_admin.import_comments') }}">Import</a></li>
              </ul>
            </li>
            {% endif %}

            {% if g.identity.allow_admin %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Users <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('accounts.users') }}">All Users</a></li>
                <li><a href="{{ url_for('accounts.add_user') }}">New User</a></li>
                <!-- <li class="divider"></li>
                <li><a href="#">User Groups</a></li> -->
                <!-- <li class="divider"></li>
                <li><a href="#">Category</a></li> -->
              </ul>
            </li>
            {% endif %}

            {% if g.identity.allow_admin %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Super Admin <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('blog_admin.su_posts') }}">Super Posts</a></li>
                <li><a href="{{ url_for('accounts.su_users') }}">Users</a></li>
                <li class="divider"></li>
                <li><a href="{{ url_for('blog_admin.su_widgets') }}">Widget</a></li>
                <li class="divider"></li>
                <li><a href="{{ url_for('blog_admin.post_statistics') }}">Posts Statistics</a></li>
                <li class="divider"></li>
                <li><a href="#">Import</a></li>
                <li><a href="{{ url_for('blog_admin.su_export') }}">Export</a></li>                
              </ul>
            </li>
            {% endif %}

          </ul>
          
            

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ current_user.username }} <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('accounts.settings') }}">Settings</a></li>
                <li><a href="#">Import/Export</a></li>
                <li class="divider"></li>
                <li><a href="{{ url_for('accounts.logout') }}">Logout</a></li>
                <!-- <li class="divider"></li>
                <li><a href="#">Category</a></li> -->
              </ul>
            </li>
          {% else %}
            <li><a href="{{ url_for('accounts.login') }}">Login</a></li>
            <li><a href="{{ url_for('accounts.register') }}">Register</a></li>
          {% endif %}
          </ul>
        </div>
      </div><!-- /.container-fluid -->
    </nav>


    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    {%block header %}{% endblock %}
    <div class="container">
        <!-- Main Content -->
        
        {%block main %}{% endblock %}
    </div>
    <hr>
    
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="https://creativecommons.org/licenses/" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-creative-commons fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-rss fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/flyhigher139/OctBlog" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted text-center">Copyright &copy; Oct Blog 2015</p>
                </div>
            </div>
        </div>
    </footer>
    <!-- jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>
    
    <!-- Custom Theme JavaScript -->
    {% block js %}
    {% endblock %}
    
</body>
</html>